spring:
  datasource:
    #url: jdbc:mysql://127.0.0.1:3306/jgybzx?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useAffectedRows=true
    url: jdbc:mysql://123.57.218.169:3306/jgybzx?useUnicode=true&characterEncoding=UTF8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  #配置项目热部署 spring.devtools.restart.enabled=true
  devtools:
    restart:
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
mybatis:
  mapper-locations: classpath:mappers/*.xml
holiday:
  url: https://v.juhe.cn/calendar/month
  key: 73777cdcc5bef04f4cfb47afdabc4a09





